# Generated by Django 6.0.3 on 2026-04-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_chatroom_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='last_messsage',
            new_name='last_message',
        ),
    ]
