# Generated by Django 6.0.3 on 2026-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_rename_last_messsage_chatroom_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='shared_post_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
