# Generated by Django 6.0.3 on 2026-04-22 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_chatmessage_shared_post_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(blank=True, max_length=150, null=True)),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('share', 'Share'), ('message', 'Message'), ('follow_request', 'Follow Request'), ('follow_approved', 'Follow Approved')], max_length=50)),
                ('message', models.TextField()),
                ('related_post_id', models.CharField(blank=True, max_length=500, null=True)),
                ('related_comment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('related_request_id', models.IntegerField(blank=True, null=True)),
                ('related_message_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
